CLASS_SCENE = [
    # === Core ===
    "Node",
    "Node2D",
    "Node3D",
    "Resource",
    # === Physics 2D ===
    "CharacterBody2D",
    "RigidBody2D",
    "StaticBody2D",
    "AnimatableBody2D",
    "Area2D",
    "CollisionShape2D",
    "RayCast2D",
    "ShapeCast2D",
    # === Physics 3D ===
    "CharacterBody3D",
    "RigidBody3D",
    "StaticBody3D",
    "AnimatableBody3D",
    "Area3D",
    "CollisionShape3D",
    "RayCast3D",
    "ShapeCast3D",
    # === Visuals ===
    "Sprite2D",
    "AnimatedSprite2D",
    "Sprite3D",
    "AnimatedSprite3D",
    "MeshInstance2D",
    "MeshInstance3D",
    "MultiMeshInstance2D",
    "MultiMeshInstance3D",
    "GPUParticles2D",
    "GPUParticles3D",
    "CPUParticles2D",
    "CPUParticles3D",
    # === Cameras ===
    "Camera2D",
    "Camera3D",
    # === Animation & Timing ===
    "AnimationPlayer",
    "AnimationTree",
    "Tween",
    "Timer",
    # === Audio ===
    "AudioStreamPlayer",
    "AudioStreamPlayer2D",
    "AudioStreamPlayer3D",
    # === Tilemaps ===
    "TileMapLayer",
    "TileSet",
    # === Paths ===
    "Path2D",
    "Path3D",
    "PathFollow2D",
    "PathFollow3D",
    # === UI Core ===
    "Control",
    "CanvasLayer",
    "HBoxContainer",
    "VBoxContainer",
    "GridContainer",
    "MarginContainer",
    "CenterContainer",
    "Label",
    "Button",
    "TextureRect",
    "Panel",
    "ColorRect",
    "ProgressBar",
    # === Navigation ===
    "NavigationAgent2D",
    "NavigationAgent3D",
    "NavigationRegion2D",
    "NavigationRegion3D",
    # === Lights ===
    "PointLight2D",
    "DirectionalLight2D",
    "OmniLight3D",
    "SpotLight3D",
    "DirectionalLight3D",
    # === Shapes (CRITICAL - need exact property names) ===
    "RectangleShape2D",  # .size: Vector2
    "CircleShape2D",  # .radius: float
    "CapsuleShape2D",  # .radius, .height
    "ConvexPolygonShape2D",
    "BoxShape3D",  # .size: Vector3
    "SphereShape3D",  # .radius: float
    "CapsuleShape3D",  # .radius, .height
    "ConvexPolygonShape3D",
    # === Meshes (CRITICAL - need exact property names) ===
    "BoxMesh",  # .size: Vector3
    "SphereMesh",  # .radius, .height, .radial_segments
    "CylinderMesh",  # .top_radius, .bottom_radius, .height
    "CapsuleMesh",  # .radius, .height
    "PlaneMesh",  # .size: Vector2
    "QuadMesh",  # .size: Vector2
    "PrismMesh",  # .size: Vector3
    "TorusMesh",  # .inner_radius, .outer_radius
    # === Materials (CRITICAL - albedo_color not color!) ===
    "StandardMaterial3D",  # .albedo_color, .metallic, .roughness, .emission
    "CanvasItemMaterial",  # For 2D effects
    "ShaderMaterial",  # .shader, set_shader_parameter()
    # === Math Types (CRITICAL - constructors & constants) ===
    "Vector2",  # Vector2(x, y), Vector2.ZERO, .normalized()
    "Vector3",  # Vector3(x, y, z), Vector3.UP, .normalized()
    "Color",  # Color(r, g, b, a), Color.RED, Color.html("#ff0000")
    "Transform2D",  # For positioning
    "Transform3D",  # For positioning
    "Basis",  # For rotations
    "Rect2",  # For UI bounds
    # === Scene Handling ===
    "PackedScene",  # .pack(), .instantiate()
]

CLASS_SCRIPT = [
    # Core
    "Node",
    "Node2D",
    "Node3D",
    "Object",
    "RefCounted",
    "Resource",
    # Physics 2D
    "CharacterBody2D",
    "RigidBody2D",
    "StaticBody2D",
    "AnimatableBody2D",
    "Area2D",
    "CollisionShape2D",
    "CollisionPolygon2D",
    "RayCast2D",
    "ShapeCast2D",
    # Physics 3D
    "CharacterBody3D",
    "RigidBody3D",
    "StaticBody3D",
    "AnimatableBody3D",
    "Area3D",
    "CollisionShape3D",
    "CollisionPolygon3D",
    "RayCast3D",
    "ShapeCast3D",
    # Sprites & Visuals
    "Sprite2D",
    "AnimatedSprite2D",
    "Sprite3D",
    "AnimatedSprite3D",
    "MeshInstance2D",
    "MeshInstance3D",
    "MultiMeshInstance2D",
    "MultiMeshInstance3D",
    "GPUParticles2D",
    "GPUParticles3D",
    "CPUParticles2D",
    "CPUParticles3D",
    # Cameras
    "Camera2D",
    "Camera3D",
    # Animation
    "AnimationPlayer",
    "AnimationTree",
    "AnimationMixer",
    "Tween",
    "Timer",
    # Audio
    "AudioStreamPlayer",
    "AudioStreamPlayer2D",
    "AudioStreamPlayer3D",
    # Tilemaps
    "TileMapLayer",
    "TileSet",
    # Paths
    "Path2D",
    "Path3D",
    "PathFollow2D",
    "PathFollow3D",
    # UI Core
    "Control",
    "Container",
    "CanvasLayer",
    "CanvasItem",
    # UI Containers
    "HBoxContainer",
    "VBoxContainer",
    "GridContainer",
    "MarginContainer",
    "CenterContainer",
    "PanelContainer",
    "ScrollContainer",
    "AspectRatioContainer",
    # UI Elements
    "Label",
    "RichTextLabel",
    "Button",
    "TextureButton",
    "LineEdit",
    "TextEdit",
    "SpinBox",
    "Slider",
    "HSlider",
    "VSlider",
    "ProgressBar",
    "CheckBox",
    "CheckButton",
    "OptionButton",
    "ItemList",
    "Tree",
    "Panel",
    "TextureRect",
    "ColorRect",
    # Input
    "Input",  # Input.is_action_pressed(), get_axis(), etc.
    "InputEvent",
    "InputEventKey",
    "InputEventMouseButton",
    "InputEventMouseMotion",
    "InputEventAction",
    # Resources
    "PackedScene",
    "Texture2D",
    "ImageTexture",
    "AtlasTexture",
    "AudioStream",
    "AudioStreamWAV",
    "AudioStreamMP3",
    "AudioStreamOggVorbis",
    "Font",
    "FontFile",
    "Theme",
    "StyleBox",
    "Mesh",
    "ArrayMesh",
    "PrimitiveMesh",
    "BoxMesh",
    "SphereMesh",
    "CylinderMesh",
    "Material",
    "StandardMaterial3D",
    "ShaderMaterial",
    "CanvasItemMaterial",
    # Shapes
    "Shape2D",
    "RectangleShape2D",
    "CircleShape2D",
    "CapsuleShape2D",
    "ConvexPolygonShape2D",
    "Shape3D",
    "BoxShape3D",
    "SphereShape3D",
    "CapsuleShape3D",
    "ConvexPolygonShape3D",
    # Navigation
    "NavigationAgent2D",
    "NavigationAgent3D",
    "NavigationRegion2D",
    "NavigationRegion3D",
    # Lights
    "Light2D",
    "PointLight2D",
    "DirectionalLight2D",
    "Light3D",
    "OmniLight3D",
    "SpotLight3D",
    "DirectionalLight3D",
    # Math types (often needed)
    "Vector2",
    "Vector3",
    "Vector4",
    "Rect2",
    "Transform2D",
    "Transform3D",
    "Basis",
    "Quaternion",
    "AABB",
    "Plane",
    "Color",
    # Critical singletons (not nodes, but essential for scripts)
    "SceneTree",  # get_tree(), change_scene(), create_timer()
    "Engine",  # time_scale, physics ticks
    # Signal/callable (for dynamic connections)
    "Callable",
    "Signal",
    # Often manipulated in scripts
    "Curve",
    "Curve2D",
    "Curve3D",  # For paths
    "Gradient",  # For particles/effects
]

PRIORITY_CLASSES = [
    # Core
    "Node",
    "Node2D",
    "Node3D",
    "Object",
    "RefCounted",
    "Resource",
    # Physics 2D
    "CharacterBody2D",
    "RigidBody2D",
    "StaticBody2D",
    "AnimatableBody2D",
    "Area2D",
    "CollisionShape2D",
    "CollisionPolygon2D",
    "RayCast2D",
    "ShapeCast2D",
    # Physics 3D
    "CharacterBody3D",
    "RigidBody3D",
    "StaticBody3D",
    "AnimatableBody3D",
    "Area3D",
    "CollisionShape3D",
    "CollisionPolygon3D",
    "RayCast3D",
    "ShapeCast3D",
    # Sprites & Visuals
    "Sprite2D",
    "AnimatedSprite2D",
    "Sprite3D",
    "AnimatedSprite3D",
    "MeshInstance2D",
    "MeshInstance3D",
    "MultiMeshInstance2D",
    "MultiMeshInstance3D",
    "GPUParticles2D",
    "GPUParticles3D",
    "CPUParticles2D",
    "CPUParticles3D",
    # Cameras
    "Camera2D",
    "Camera3D",
    # Animation
    "AnimationPlayer",
    "AnimationTree",
    "AnimationMixer",
    "Tween",
    "Timer",
    # Audio
    "AudioStreamPlayer",
    "AudioStreamPlayer2D",
    "AudioStreamPlayer3D",
    # Tilemaps
    "TileMap",
    "TileMapLayer",
    "TileSet",
    # Paths
    "Path2D",
    "Path3D",
    "PathFollow2D",
    "PathFollow3D",
    # UI Core
    "Control",
    "Container",
    "CanvasLayer",
    "CanvasItem",
    # UI Containers
    "HBoxContainer",
    "VBoxContainer",
    "GridContainer",
    "MarginContainer",
    "CenterContainer",
    "PanelContainer",
    "ScrollContainer",
    "AspectRatioContainer",
    # UI Elements
    "Label",
    "RichTextLabel",
    "Button",
    "TextureButton",
    "LineEdit",
    "TextEdit",
    "SpinBox",
    "Slider",
    "HSlider",
    "VSlider",
    "ProgressBar",
    "CheckBox",
    "CheckButton",
    "OptionButton",
    "ItemList",
    "Tree",
    "Panel",
    "TextureRect",
    "ColorRect",
    # Input
    "InputEvent",
    "InputEventKey",
    "InputEventMouseButton",
    "InputEventMouseMotion",
    "InputEventAction",
    # Resources
    "PackedScene",
    "Texture2D",
    "ImageTexture",
    "AtlasTexture",
    "AudioStream",
    "AudioStreamWAV",
    "AudioStreamMP3",
    "AudioStreamOggVorbis",
    "Font",
    "FontFile",
    "Theme",
    "StyleBox",
    "Mesh",
    "ArrayMesh",
    "PrimitiveMesh",
    "BoxMesh",
    "SphereMesh",
    "CylinderMesh",
    "Material",
    "StandardMaterial3D",
    "ShaderMaterial",
    "CanvasItemMaterial",
    # Shapes
    "Shape2D",
    "RectangleShape2D",
    "CircleShape2D",
    "CapsuleShape2D",
    "ConvexPolygonShape2D",
    "Shape3D",
    "BoxShape3D",
    "SphereShape3D",
    "CapsuleShape3D",
    "ConvexPolygonShape3D",
    # Navigation
    "NavigationAgent2D",
    "NavigationAgent3D",
    "NavigationRegion2D",
    "NavigationRegion3D",
    # Lights
    "Light2D",
    "PointLight2D",
    "DirectionalLight2D",
    "Light3D",
    "OmniLight3D",
    "SpotLight3D",
    "DirectionalLight3D",
    # Math types (often needed)
    "Vector2",
    "Vector3",
    "Vector4",
    "Rect2",
    "Transform2D",
    "Transform3D",
    "Basis",
    "Quaternion",
    "AABB",
    "Plane",
    "Color",
]

# Unified list for both scene and script generation (99% scene / 95% script coverage)
CLASS_UNIFIED = [
    # === Core ===
    "Node",
    "Node2D",
    "Node3D",
    "Object",
    "RefCounted",
    "Resource",
    # === Physics 2D ===
    "CharacterBody2D",
    "RigidBody2D",
    "StaticBody2D",
    "AnimatableBody2D",
    "Area2D",
    "CollisionShape2D",
    "CollisionPolygon2D",
    "RayCast2D",
    "ShapeCast2D",
    # === Physics 3D ===
    "CharacterBody3D",
    "RigidBody3D",
    "StaticBody3D",
    "AnimatableBody3D",
    "Area3D",
    "CollisionShape3D",
    "CollisionPolygon3D",
    "RayCast3D",
    "ShapeCast3D",
    # === Sprites & Visuals ===
    "Sprite2D",
    "AnimatedSprite2D",
    "Sprite3D",
    "AnimatedSprite3D",
    "MeshInstance2D",
    "MeshInstance3D",
    "MultiMeshInstance2D",
    "MultiMeshInstance3D",
    "GPUParticles2D",
    "GPUParticles3D",
    "CPUParticles2D",
    "CPUParticles3D",
    # === Cameras ===
    "Camera2D",
    "Camera3D",
    # === Animation & Timing ===
    "AnimationPlayer",
    "AnimationTree",
    "Tween",
    "Timer",
    # === Audio ===
    "AudioStreamPlayer",
    "AudioStreamPlayer2D",
    "AudioStreamPlayer3D",
    # === Tilemaps ===
    "TileMapLayer",
    "TileSet",
    # === Paths ===
    "Path2D",
    "Path3D",
    "PathFollow2D",
    "PathFollow3D",
    "Curve2D",
    "Curve3D",
    # === UI Core ===
    "Control",
    "Container",
    "CanvasLayer",
    "CanvasItem",
    # === UI Containers ===
    "HBoxContainer",
    "VBoxContainer",
    "GridContainer",
    "MarginContainer",
    "CenterContainer",
    "PanelContainer",
    "ScrollContainer",
    # === UI Elements ===
    "Label",
    "Button",
    "TextureButton",
    "LineEdit",
    "ProgressBar",
    "Slider",
    "HSlider",
    "VSlider",
    "CheckBox",
    "Panel",
    "TextureRect",
    "ColorRect",
    # === Input ===
    "Input",
    "InputEvent",
    # === Resources ===
    "PackedScene",
    "Texture2D",
    "AudioStream",
    "Mesh",
    "Material",
    "StandardMaterial3D",
    "ShaderMaterial",
    "CanvasItemMaterial",
    # === Shapes ===
    "Shape2D",
    "RectangleShape2D",
    "CircleShape2D",
    "CapsuleShape2D",
    "ConvexPolygonShape2D",
    "Shape3D",
    "BoxShape3D",
    "SphereShape3D",
    "CapsuleShape3D",
    "ConvexPolygonShape3D",
    # === Meshes ===
    "PrimitiveMesh",
    "BoxMesh",
    "SphereMesh",
    "CylinderMesh",
    "CapsuleMesh",
    "PlaneMesh",
    # === Navigation ===
    "NavigationAgent2D",
    "NavigationAgent3D",
    "NavigationRegion2D",
    "NavigationRegion3D",
    # === Lights ===
    "Light2D",
    "PointLight2D",
    "DirectionalLight2D",
    "Light3D",
    "OmniLight3D",
    "SpotLight3D",
    "DirectionalLight3D",
    # === Math types ===
    "Vector2",
    "Vector3",
    "Vector4",
    "Rect2",
    "Transform2D",
    "Transform3D",
    "Basis",
    "Quaternion",
    "AABB",
    "Plane",
    "Color",
    # === Singletons/utilities ===
    "SceneTree",
    "Engine",
    "Callable",
    "Signal",
]

KEY_CODES = {
    "W": 87,
    "A": 65,
    "S": 83,
    "D": 68,
    "Up": 4194320,
    "Down": 4194322,
    "Left": 4194319,
    "Right": 4194321,
    "Space": 32,
    "Enter": 4194309,
    "Escape": 4194305,
    "Shift": 4194328,
    "Ctrl": 4194326,
    "Alt": 4194332,
    "Mouse1": 1,
    "Mouse2": 2,
}
